FootballApp/FootballApp/Controllers/PlayedMatchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FootballApp.Data;
using FootballApp.Models;

namespace FootballApp.Controllers
{
    public class PlayedMatchesController : Controller
    {
        private FootballAppContext db = new FootballAppContext();

        // GET: PlayedMatches
        public ActionResult Index()
        {
            var playedMatches = db.PlayedMatches.Include(p => p._team);
            return View(playedMatches.ToList());
        }

        // GET: PlayedMatches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlayedMatch playedMatch = db.PlayedMatches.Find(id);
            if (playedMatch == null)
            {
                return HttpNotFound();
            }
            return View(playedMatch);
        }

        // GET: PlayedMatches/Create
        public ActionResult Create()
        {
            ViewBag.TeamID = new SelectList(db.Teams, "ID", "Name");
            return View();
        }

        // POST: PlayedMatches/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TeamID,_result,GoalsScored,GoalsConceded")] PlayedMatch playedMatch)
        {
            if (ModelState.IsValid)
            {
                db.PlayedMatches.Add(playedMatch);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TeamID = new SelectList(db.Teams, "ID", "Name", playedMatch.TeamID);
            return View(playedMatch);
        }

        // GET: PlayedMatches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlayedMatch playedMatch = db.PlayedMatches.Find(id);
            if (playedMatch == null)
            {
                return HttpNotFound();
            }
            ViewBag.TeamID = new SelectList(db.Teams, "ID", "Name", playedMatch.TeamID);
            return View(playedMatch);
        }

        // POST: PlayedMatches/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TeamID,_result,GoalsScored,GoalsConceded")] PlayedMatch playedMatch)
        {
            if (ModelState.IsValid)
            {
                db.Entry(playedMatch).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TeamID = new SelectList(db.Teams, "ID", "Name", playedMatch.TeamID);
            return View(playedMatch);
        }

        // GET: PlayedMatches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlayedMatch playedMatch = db.PlayedMatches.Find(id);
            if (playedMatch == null)
            {
                return HttpNotFound();
            }
            return View(playedMatch);
        }

        // POST: PlayedMatches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PlayedMatch playedMatch = db.PlayedMatches.Find(id);
            db.PlayedMatches.Remove(playedMatch);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FootballApp/FootballApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Football App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FootballApp Main Site", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Footballers", "Index", "Footballers")</li>
                    <li>@Html.ActionLink("Teams", "Index", "Teams")</li>
                    <li>@Html.ActionLink("Played matches", "Index", "PlayedMatches")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FootballApp ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FootballApp/FootballApp/Views/Shared/_Layout_list.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title] - Football App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FootballApp ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FootballApp/FootballApp/Views/Shared/_Layout_matches.cshtml
    <!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Football App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FootballApp Main Site", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Footballers", "Index", "Footballers")</li>
                    <li>@Html.ActionLink("Teams", "Index", "Teams")</li>
                    <li>@Html.ActionLink("Played matches", "Index", "PlayedMatches")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FootballApp ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FootballApp/FootballApp/Views/Shared/_Layout_start.cshtml
    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Football App</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="choose">
            
                @Html.ActionLink("Footballers", "Index", "Footballers")
            
            <img width="90%" src="https://static.sportzbusiness.com/uploads/2020/01/Footballers.jpg" />
        </div>
        <div class="choose">
            
                @Html.ActionLink("Teams", "Index", "Teams")
            
            <img width="90%" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Greece_U-21-national_football_team_2011-09-05_%2801%29.jpg/800px-Greece_U-21-national_football_team_2011-09-05_%2801%29.jpg" />
        </div>
        <div class="choose">
            
                @Html.ActionLink("Played matches", "Index", "PlayedMatches")
            
            <img width="90%" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/HB_-_NSI_football_match_02.jpg/800px-HB_-_NSI_football_match_02.jpg" />
        </div>
        <div style="clear:both;"></div>
        <div class="container body-content">
            @RenderBody()

            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - FootballApp ASP.NET</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

FootballApp/FootballApp/Views/Shared/_randomFootballer.cshtml
@model FootballApp.Models.Footballer

@{
    ViewBag.Title = "RandomFootballer";
}

<div class="random-footballer">
    <h2>Random Footballer from Database:</h2>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>
</div>